name: Build

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install conan
        run: |
          python -m pip install --user conan
      - name: Setup conan
        run: |
          conan profile detect -f
      - name: s/x86_64/x86/g s/dynamic/static/g
        shell: python
        run: |
          import subprocess
          
          path_default_profile = subprocess.check_output(["conan", "profile", "path", "default"], text=True).strip()
          txt = open(path_default_profile).read()
          open(path_default_profile, "w").write(txt.replace("x86_64", "x86").replace("dynamic", "static"))
      - name: Build carm95_detours
        run: |
          conan build . --output-folder=build --build=missing

          cd build
          cpack . -C Release -G ZIP
      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: carm95hooks
          path: build/carm95hooks.zip
